Egor barkalov/cod 11 отображение страниц используя react router и react router
mlashina13/coder pull request #13
Opened 2023-11-18 20:01 UTC by ostroovok

Добавил роутер в проект

2023-11-18 20:05 UTC, KonovalovaES commented on packages/client/src/components/AuthHeader/AuthHeader.tsx
> +  const handleChange = (_: SyntheticEvent, path: LoginTabsPaths) => {
так как функция не возвращает значение, предлагаю записать в строчку в круглых скобках

2023-11-18 20:06 UTC, KonovalovaES commented on packages/client/src/constants/routes.tsx
удобно, что константы названы в UpperCase – повышается читаемость кода

2023-11-18 20:08 UTC, KonovalovaES reviewed
Супер, что появился роутинг. Одно небольшое замечание в компоненте AuthHeader, возможно, вкусовщина :)

2023-11-18 20:12 UTC, KonovalovaES approved these changes

2023-11-18 20:13 UTC, kirillmuz approved these changes
Вцелом все хорошо, есть мелкое замечание к файлу App.tsx

2023-11-18 20:13 UTC, kirillmuz commented on packages/client/src/App.tsx
>      <Box>
Думаю, здесь не нужно оборачивать AppRouter в Box, можно просто его ретернить из App

2023-11-18 20:23 UTC, mlashina13 approved these changes
Проверила, есть маленькое замечание

2023-11-18 20:23 UTC, mlashina13 commented on packages/client/src/constants/routes.tsx
> +  Leaderboard: '/Leaderboard',
Хотелось бы, чтобы все ссылки начинались с маленькой буквы

2023-11-18 20:29 UTC, ostroovok commented on packages/client/src/components/AuthHeader/AuthHeader.tsx
> +  const handleChange = (_: SyntheticEvent, path: LoginTabsPaths) => {
Fixed

2023-11-18 20:29 UTC, ostroovok commented on packages/client/src/App.tsx
>      <Box>
Fixed

2023-11-19 14:56 UTC, IvanPeleshok requested changes
Проделана большая работа!
Отлично потрудились!

Есть небольшие замечания, предлагаю доработь

Хорошего дня :)

2023-11-19 14:56 UTC, IvanPeleshok commented on packages/client/src/components/AuthHeader/AuthHeader.tsx
> +    key: LOGIN_ROUTES.Login as LoginTabsPaths,
Не очень понимаю для чего кастить тип? Что-то подсказывает, что он будет неверный для значения поля key
Предлагаю следующее: 
```
export const ROUTER_URLS = {
 ...
} as const

type Keys = keyof typeof LOGIN_ROUTES;
type Values = typeof LOGIN_ROUTES[Keys];

const TABS_KEYS: Record<
  string,
  {
    key: Values;
    ...
```

В подобном случае кастить тип не придётся, там будут юнион тип со значениями 'login' | 'registration' или что-то в этом роде

2023-11-19 14:56 UTC, IvanPeleshok commented on packages/client/src/constants/routes.tsx
> +  Leaderboard: '/Leaderboard',
По аналогии с маленькой буквы (как и другие пути)

2023-11-19 18:04 UTC, ostroovok commented on packages/client/src/components/AuthHeader/AuthHeader.tsx
> +    key: LOGIN_ROUTES.Login as LoginTabsPaths,
в этом случае key будет стринг, а при вводе иного значения ошибки нет
![image](https://github.com/mlashina13/coder/assets/71485188/e982507d-61c9-4052-96b7-361123cc3d46)

2023-11-20 07:38 UTC, IvanPeleshok commented on packages/client/src/components/AuthHeader/AuthHeader.tsx
> +    key: LOGIN_ROUTES.Login as LoginTabsPaths,
@ostroovok FYI
<img width="583" alt="image" src="https://github.com/mlashina13/coder/assets/70073003/b3f6e058-074c-4f70-a29c-2d57aee41e0b">
<img width="736" alt="image" src="https://github.com/mlashina13/coder/assets/70073003/bdf699b8-52f8-41d0-91ea-51fee0474b03">

2023-11-20 07:39 UTC, IvanPeleshok approved these changes
Поздравляю, работа принята!

Хорошего дня :)

2023-11-20 12:24 UTC, merged