Ekaterinaskonovalova/cod 14 верстка страницы ошибок 500 05
mlashina13/coder pull request #17
Opened 2023-11-20 08:07 UTC by KonovalovaES

- Добавлен базовый компонент Error.
- Добавлена страница для отображения 400-х ошибок Error400Page.
- Добавлена страница для отображения 500-х ошибок Error500Page.

Здесь я объединила 2 задачи в одну, так как они аналогичные (вывод 500-х и 400-х ошибок). Также не добавляла роутинг, потому что его еще нет в общей ветке, но для добавления роутов всех страниц есть отдельная задача.

По умолчанию уже заданы коды ошибок и их описания:
- 500 "Произошла ошибка сервера";
- 404 "Страница не существует".

При необходимости код, описание ошибки и текст внутри кнопки можно будет менять с помощью пропсов.

Предполагаю, что заглушки действий при клике по кнопке на странице ошибок можно будет исправить после того, как появится обработчик ошибок.

2023-11-20 08:41 UTC, mlashina13 approved these changes
Проверено, замечаний нет

2023-11-20 09:12 UTC, kirillmuz requested changes
Все очень хорошо и аккуратно написано, код читается легко, хорошая структура.
Есть небольшие замечания, которые стоит поправить

2023-11-20 09:12 UTC, kirillmuz commented on packages/client/src/assets/icons/Error400Icon.tsx
> +    fill={color || '#525252'}
я бы вынес задание дефолтного цвета в деструктуризацию пропсов, по аналогии с height и width

2023-11-20 09:12 UTC, kirillmuz commented on packages/client/src/assets/icons/Error500Icon.tsx
> +    fill={color || '#525252'}
fill аналогично предыдущему файлу

2023-11-20 09:12 UTC, kirillmuz commented on packages/client/src/components/Error/Error.tsx
> +    <>
Фрагмент не нужен, т.к. группа компонентов обернута в Box

2023-11-20 09:12 UTC, kirillmuz commented on packages/client/src/components/Error/errorStyles.scss
Предлагаю использовать функционал препроцессора и поместить стили элементов внутрь блока:
.error-page {
    &__content {
        ...
    }

    &__code {
        ...
    }

    &__description {
        ...
    }
}

Это сократит код и сделает его более наглядным, показав иерархию компонентов. Также если мы захотим переименовать класс error-page, то нам не придется менять его везде вручную, т.к. его имя применится к вложенным класам через &

2023-11-20 09:22 UTC, KonovalovaES commented on packages/client/src/assets/icons/Error400Icon.tsx
> +    fill={color || '#525252'}
Согласна, исправила

2023-11-20 09:22 UTC, KonovalovaES commented on packages/client/src/assets/icons/Error500Icon.tsx
> +    fill={color || '#525252'}
Согласна, исправила

2023-11-20 09:23 UTC, KonovalovaES commented on packages/client/src/components/Error/Error.tsx
> +    <>
Согласна, исправила – изначально подсвечивалась ошибка, поэтому добавляла фрагмент, а потом забыла вернуться к этой части)

2023-11-20 09:23 UTC, KonovalovaES commented on packages/client/src/components/Error/errorStyles.scss
Согласна, исправила

2023-11-21 07:36 UTC, kirillmuz approved these changes

2023-11-21 08:16 UTC, merged