Поправка сталей ля форм регистрации и авторизации
mlashina13/coder pull request #18
Opened 2023-11-22 15:20 UTC by mlashina13

Добавление страниц в роутинг

Поправка сталей ля форм регистрации и авторизации
Добавление страниц в роутинг

2023-11-25 14:53 UTC, KonovalovaES requested changes
Все отлично, есть только пара мелких замечаний

2023-11-25 14:53 UTC, KonovalovaES commented on packages/client/src/components/common/menu/Menu.tsx
> +  const { menuItems, defaultSelected } = props;
Предлагаю деструктуризацию сразу в аргументах применять – props больше нигде не используется в компоненте, поэтому сократим строчку, но ничего не потеряем от этого

2023-11-25 14:53 UTC, KonovalovaES commented on packages/client/src/components/common/menu/Menu.tsx
> +        {menuItems.map((r) => (
На мой взгляд r – не совсем очевидное название, item более наглядно показывает, с чем работаем

2023-11-25 14:53 UTC, KonovalovaES commented on packages/client/src/components/layout/Layout.tsx
> +
Кажется, здесь лишняя пустая строчка

2023-11-25 14:53 UTC, KonovalovaES commented on packages/client/src/constants/routes.tsx
> +   * Мтраница "Правила игры"
Опечатка

2023-11-26 19:23 UTC, mlashina13 commented on packages/client/src/components/common/menu/Menu.tsx
> +        {menuItems.map((r) => (
Поправила

2023-11-26 19:23 UTC, mlashina13 commented on packages/client/src/components/layout/Layout.tsx
> +
Поправила

2023-11-26 19:23 UTC, mlashina13 commented on packages/client/src/constants/routes.tsx
> +   * Мтраница "Правила игры"
Поправила

2023-11-26 19:24 UTC, mlashina13 commented on packages/client/src/components/common/menu/Menu.tsx
> +  const { menuItems, defaultSelected } = props;
Поправила!

2023-11-27 06:17 UTC, KonovalovaES approved these changes

2023-11-27 09:42 UTC, merged