#cod-41 Компонент основного лейаута приложения
mlashina13/coder pull request #2
Opened 2023-11-14 22:49 UTC by kirillmuz

Добавлены компоненты основного layout'а приложения:
- Шапка
- Панель навигации
- Компонент вспомогательного меню (прокидывается через render props)
- Настроены базовые стили контейнера под контент страниц

Отдельно создан компонент меню, который можно использовать для построения вспомогательного меню на странице игры

Доработаны общие стили
Цвета, отступы и размеры добавлял без файлов констант, т.к. ожидаю выполнения задачи с данным функционалом от коллег
Добавил несколько новых правил для линтера

![image](https://github.com/mlashina13/coder/assets/13846959/818b9e57-6e17-4d2c-8b52-262ce2eec6d5)

https://github.com/mlashina13/coder/assets/13846959/b284d30f-395a-4433-9a1a-63721b5fa26c

2023-11-14 22:50 UTC, kirillmuz commented
Подключение Layout'а:

<Layout subMenu={
	<Menu selectedChanged={() => console.log('')} menuItems={[
            {id: 0, label: 'Правила игры'},
            {id: 1, label: 'Результаты'},
            {id: 2, label: 'Начать'},
        ]}
        defaultSelected={0}
        />
    }
    title="Название страницы"
>
    <Box>Здесь будет контент страницы</Box>
</Layout>

2023-11-15 10:01 UTC, andreymesh approved these changes
Отлично, что начали настраивать линтер, должно облегчить дальнейшую разработку.
Плюс за пример использования компонента-обертки

2023-11-15 11:44 UTC, mlashina13 commented on packages/client/src/components/layout/navigationPanel/NavigationPanel.tsx
Необходимо вынести параметры для  настройки навигации в роутер
```
const routes = [{
    key: 'forum',
    path: '/forum',
    name: 'Форум',
    icon: <Icon />
},
```

2023-11-15 11:57 UTC, mlashina13 commented on packages/client/src/components/common/menu/Menu.tsx
```
/**
   * Убираем элементы, id которых повторяется в наборе
   */
  const uniqueItems: Array<MenuItem> = useMemo(() => {
    return menuItems.reduce((prev, curr) => {
      return prev.some(p => p.id === curr.id) ? prev : [...prev, curr]
    }, [] as Array<MenuItem>)
  }, [menuItems])
```
Не согласна с тем, что в этой функции удаляются повторяющиеся элементы, так как, если разработчик добавил новый элемент, и увидел, что он не отобразился, ему придется лезть в код и искать причину. Здесь следовало бы выкинуть ошибку, о совпадении идентификаторов.

2023-11-15 12:11 UTC, mlashina13 commented on packages/client/src/types/common.ts
```
 /**
   * Идентификатор
   */
  id: number | string
```
Не понятно, почему идентификатор может иметь 2 типа данных, это переменная должна содержать уникальные значения, но одного типа.
Например, если у нас идентификатор число 1 или строка "1" - это будет считаться как одно и тоже, или это разные вещи...

2023-11-15 12:14 UTC, mlashina13 requested changes
Просьба посмотреть и поправить замечания.

2023-11-15 12:17 UTC, kirillmuz commented on packages/client/src/components/common/menu/Menu.tsx
Да тут забыл дописать, собирался выводить в консоль warning с пояснением

2023-11-15 20:57 UTC, kirillmuz commented on packages/client/src/components/layout/navigationPanel/NavigationPanel.tsx
Готово

2023-11-15 20:57 UTC, kirillmuz commented on packages/client/src/components/common/menu/Menu.tsx
Поправил

2023-11-15 20:58 UTC, kirillmuz commented on packages/client/src/types/common.ts
Исправлено

2023-11-15 21:06 UTC, mlashina13 approved these changes
Все отлично, замечания поправлены

2023-11-15 21:10 UTC, merged