#COD-49 Реализовать состояние «Начало» и состояние «Завершение игры» (3)
mlashina13/coder pull request #22
Opened 2023-12-01 20:11 UTC by mlashina13

Задача:  Реализовать состояние «Начало» и состояние «Завершение игры»

Перед запуском игры, открывается форма настроек, в которой необходимо заполнить обязательные поля, после чего блокируются поля настроек,  открывается игра, и запускается таймер. Если таймер был установлен в настройках, то  запускается указанное время, если поле было пустым, то таймер выставляется на 1 минуту. 
![image](https://github.com/mlashina13/coder/assets/143003953/ba00b986-5932-4309-94da-a0a629e37ff6)

Как только времени остается, меньше 10с, таймер окрашивается в красный цвет
![image](https://github.com/mlashina13/coder/assets/143003953/4e294341-4290-4a5c-a18e-e1f762ffd0c1)

Если пользователь не успел в указанное время завершить игру, появляется диалоговое окно с ошибкой

После чего можно либо запустить игру заново, либо повторить эту же игру, или перейти на главную страницу. 
Ели пользователь выбрал играть снова, то открывается форма настроек

Если пользователь выиграл, ему выдается диалоговое окно с его результатами
![image](https://github.com/mlashina13/coder/assets/143003953/214f6425-1c7d-46b4-b46d-79628c93761f)

Где пользователь, так же может сыграть заново, или перейти на главную страницу или страницу с интересными фактами, которая ему стала доступна.
![image](https://github.com/mlashina13/coder/assets/143003953/800f8a65-c3ac-4de0-aec7-da7aa76345b2)

2023-12-01 20:42 UTC, kirillmuz commented on packages/client/src/components/GameField/Game/helpers/index.ts
> +  console.log(sequence);
Точно нужно, или забыла убрать?

2023-12-01 21:51 UTC, mlashina13 commented on packages/client/src/components/GameField/Game/helpers/index.ts
> +  console.log(sequence);
Точно нужно, это проверять загаданную последовательность. А то долго разгадывать :)

2023-12-01 22:09 UTC, kirillmuz requested changes
В целом, все хорошо! Есть пара замечаний, которые надо поправить и ряд предложений, которые можно по желанию применить в коде

2023-12-01 22:09 UTC, kirillmuz commented on packages/client/src/pages/GamePages/SettingsPage/SettingsGameProviderTypes.ts
> +  time: string;
тут лучше использовать тип number

2023-12-01 22:09 UTC, kirillmuz commented on packages/client/src/pages/GamePages/SettingsPage/SettingsGameProviderTypes.ts
> +  colorsCount: string;
тут лучше использовать тип number

2023-12-01 22:09 UTC, kirillmuz commented on packages/client/src/pages/GamePages/SettingsPage/SettingsGameProviderTypes.ts
> +  stepsCount: string;
тут лучше использовать тип number

2023-12-01 22:09 UTC, kirillmuz commented on packages/client/src/components/GameField/GameField.tsx
> +  const [seconds, setSeconds] = useState<number>(Number(time) * 60);
Лучше в settings типизировать тип, как number, тогда не придется приводить к типу здесь

2023-12-01 22:09 UTC, kirillmuz commented on packages/client/src/components/GameField/GameField.tsx
> +            <span className={isDanger ? 'text-danger' : 'text-slate'}>
Я бы предложил немного поменять структуру css стилей, опишу в комменте к gameFieldStyles.scss

2023-12-01 22:09 UTC, kirillmuz commented on packages/client/src/components/GameField/gameFieldStyles.scss
> +.text-danger {
Чтобы соответствовать BEM, я бы поменял структуру и нейминг некоторых стилей, например вот так:
.game-field {
  &__buttons-block {
    ...
  }

  &__timer { // вместо text-danger
    &__slate {
      ...
    }
    &_danger {
      ...
    }
  }
}
И применил бы соответствующую структуру в компоненте

2023-12-01 22:09 UTC, kirillmuz commented on packages/client/src/components/GameField/GameField.tsx
>        {result ? (
Довольно сложные условия в разметке- тяжело читать, можно их разбить например вынеся в отдельную функцию-рендерер и уже ее вызывать внутри блока return:
```
const contentRenderer = () => {
    if(!result){
      return (
        <Box>
            <Container className='game-page__buttons-block'>
              ...
            </Container>
            ...
          </Box>
      )
    }

    if(result.isWin){
      return (<EndGameDialog
        ...
      />);
    }

    return (<EndGameFailDialog
      ...
    />)
  }

  return (
    <Box className='game-field'>
      {contentRenderer()}
    </Box>
  );

```

2023-12-01 22:09 UTC, kirillmuz commented on packages/client/src/pages/GamePages/SettingsPage/EndGameForm/EndGameDialog.scss
Некритично, но в данном файле можно поправить нейминг стилей:
__content__icon -> __content-icon
__content__field  -> __content-field
и т.д.

 По BEM это покажет, что эти стили описывают конкретные элементы, а сейчас имена больше похожи на то, будто они описывают модификаторы

2023-12-01 22:09 UTC, kirillmuz commented on packages/client/src/pages/GamePages/InformationsPage/InformationsPage.tsx
> +          <Box component={Link} to={`/info/${image.id}`}>
Надо поставить свойство key у итерируемых объектов, чтобы реакт мог оптимально и без ошибок их рендерить. Коротеньий и достаточно информативный видос на эту тему:
https://www.youtube.com/watch?v=OtAlPwW8DNU&ab_channel=%D0%90%D0%B9%D0%A2%D0%B8%D0%A1%D0%B8%D0%BD%D1%8F%D0%BA

2023-12-01 23:42 UTC, mlashina13 commented on packages/client/src/pages/GamePages/SettingsPage/SettingsGameProviderTypes.ts
> +  time: string;
Поправила

2023-12-01 23:43 UTC, mlashina13 commented on packages/client/src/pages/GamePages/SettingsPage/SettingsGameProviderTypes.ts
> +  colorsCount: string;
Поправила

2023-12-01 23:43 UTC, mlashina13 commented on packages/client/src/pages/GamePages/SettingsPage/SettingsGameProviderTypes.ts
> +  stepsCount: string;
Поправила

2023-12-01 23:43 UTC, mlashina13 commented on packages/client/src/components/GameField/GameField.tsx
> +  const [seconds, setSeconds] = useState<number>(Number(time) * 60);
Поправила

2023-12-01 23:43 UTC, mlashina13 commented on packages/client/src/components/GameField/GameField.tsx
> +            <span className={isDanger ? 'text-danger' : 'text-slate'}>
Поправила

2023-12-01 23:44 UTC, mlashina13 commented on packages/client/src/components/GameField/GameField.tsx
>        {result ? (
Поправила! Спасибо за замечание!

2023-12-01 23:44 UTC, mlashina13 commented on packages/client/src/pages/GamePages/SettingsPage/EndGameForm/EndGameDialog.scss
Поправила

2023-12-01 23:44 UTC, mlashina13 commented on packages/client/src/pages/GamePages/InformationsPage/InformationsPage.tsx
> +          <Box component={Link} to={`/info/${image.id}`}>
Поправила! Спасибо за видео!

2023-12-01 23:52 UTC, kirillmuz approved these changes
Все хорошо, замечания поправлены

2023-12-02 08:27 UTC, Olegas requested changes
Добрый день.
По сути задачи все в порядке, есть замечания по деталям реализации.
Нужно доработать.

2023-12-02 08:27 UTC, Olegas commented on packages/client/src/components/GameField/GameField.tsx
> +            return Math.max(Number(second) - 1, 0);
А для чего здесь нужно приведение к числу? Кажется это лишняя операция здесь. И Как здесь может пригодиться max? Ведь если секунды = 0 то мы сюда не попадем, а если они больше 0 то уменьшение на 1 даст в худшем случае 0, отрицательного быть не может

2023-12-02 08:27 UTC, Olegas commented on packages/client/src/pages/GamePages/InformationsPage/InformationsPage.tsx
> +  }, []);
Для чего тут useEffect? Можно сразу при вызове useState указать начальное значение

2023-12-02 08:27 UTC, Olegas commented on packages/client/src/pages/GamePages/SettingsPage/SettingsProvider.tsx
>  export const SettingGame = () => useContext(SettingGameContext);
Хук для получения данных из контекста обычно а) называют с маленькой буквы (ведь это не компонент) и б) начинают название с use (ведь это хук)

2023-12-02 08:27 UTC, Olegas commented on packages/client/src/components/GameField/GameField.tsx
>      if (!canvasRef.current || !ctx) {
Здесь можно убрать проверку на canvasRef.current т.к. если его нет, выше не будет заполнен ctx

2023-12-02 10:59 UTC, mlashina13 commented on packages/client/src/components/GameField/GameField.tsx
> +            return Math.max(Number(second) - 1, 0);
Замечание поправлено

2023-12-02 10:59 UTC, mlashina13 commented on packages/client/src/pages/GamePages/InformationsPage/InformationsPage.tsx
> +  }, []);
Удален useEffect, перенесено начальное состояние в useState

2023-12-02 11:00 UTC, mlashina13 commented on packages/client/src/pages/GamePages/SettingsPage/SettingsProvider.tsx
>  export const SettingGame = () => useContext(SettingGameContext);
Поправлено

2023-12-02 11:01 UTC, mlashina13 commented on packages/client/src/components/GameField/GameField.tsx
>      if (!canvasRef.current || !ctx) {
Проверку оставила, так как по коду в else, ругается что  canvasRef.current может быть null, тогда нужно ставить дополнительную проверку
` if (!canvasRef.current || !ctx) {
      console.warn('Не найден элемент canvas или его контекст');
    } else {
      setGame(
        new Game(
          canvasRef.current,
          ctx,
          onEndGame,
          settings.colorsCount,
          settings.stepsCount,
          Boolean(settings.isColorsMayBeRepeated)
        )
      );
    }`

2023-12-02 15:22 UTC, Olegas approved these changes
Работа принята

2023-12-02 20:10 UTC, merged