Kirillmuz/cod 64 реализовать api для форума 5
mlashina13/coder pull request #36
Opened 2024-01-13 01:34 UTC by kirillmuz

Добавлен API форума

2024-01-13 07:55 UTC, mlashina13 approved these changes
Отличная работа!

2024-01-13 11:41 UTC, Olegas requested changes
Добрый день.
Есть замечания к роеализации:
1. Не описано ни одного индекса, при этом есть отбор ответов по commentId и комментариев по topicId. На эти поля нужны индексы
2. Идентификатор автора у вас берется из данных запроса. Это плохо, т.к. любой может подставить туда любые данные. Лучше брать эти данные из модлвары авторизации
3. При удалении и изменении сущностей нет проверок на то, кто делает изменение. Получается любой может поменять чужие данные
4. Не понятно зачем количество сообщение сделано в отдельном поле - эту информацию можно получать на лету из базы данных

2024-01-14 09:43 UTC, Olegas requested changes
Все здорово, кроме учета количества комментариев и ответов.
Сейчас получилось очень  затратное с точки зрения базы данных решение. Это проблема N+1 - чем больше у нас комментариев и ответов, тем больше будет вложенных запросов. Сложность тут еще в том, что у вас структура таблиц - топик <- комментарий <- ответ. А считать вы хотите количество всех вложенных объектов. Если это делать напрямую из базы, это будет очень ресурсозатратно, вам придется поднять все комментариий что бы получить их идентификатор и затем по ним посчитать ответы. 
Также, обратите внимание, что получать все элементы а потом считать из на стороне JS также не правильно и ресурсозатратно. В SQL есть оператор COUNT который позволяет получить кол-во записей и передать на сторону JS одно число.
Предлагаю такое решение:
1. комментарии и ответы сложить в одну таблицу. Пусть там будет ссылка на топик и ссылка на родительскую запись. То есть комментарии и ответы - это одно и то же, просто у комментария ссылка на родителя - null, а у ответа - родитель это комментарий. И у всех есть ссылка на топик
2. Расчет количества превращается в простейший запрос SELECT COUNT(id) FROM table WHERE topicId = ?. При наличии индекса на поле topicId (а он вам обязательно нужен, как, кстати, и по полю "ид родителя") это будет очень быстро и эффективно
Для решения этой проблемы лучше сделать так

2024-01-14 14:39 UTC, Olegas commented on packages/server/dal/models/comment.ts
> +  parentId!: number | null;
Совет на будущее: тут надо использовать foreign key, такой же как выше topic, тогда при удалении достаточно удалить родительский элемент и все дочерние будут удалены сами

2024-01-14 14:39 UTC, Olegas approved these changes
Отлично! Работа принята

2024-01-14 14:49 UTC, kirillmuz commented on packages/server/dal/models/comment.ts
> +  parentId!: number | null;
Понял, спасибо

2024-01-14 16:13 UTC, merged