Egor barkalov/cod 65 переключение тем клиентская часть 2
mlashina13/coder pull request #39
Opened 2024-01-14 12:10 UTC by ostroovok

Добавлены стили для темной темы, переключатель слева в шапке приложения. Переключение происходит посредством сохранения на сервер через userId, POST - api/theme/save:
```
{
    userId: string,
    theme: string
}
```
Получение значения темы при входе в приложение: 
GET - api/theme/{:id}

Так же значение сохраняется в localStorage, что позволяет не вошедшему пользователю увидеть ранее выбранную тему на странице входа/регистрации.

Тема реализуется через глобальные переменные стилей в globalStyles.scss. Цвета используются повсеместно в проекте, что позволяет изменять темы как вместе, так и по отдельности или добавлять новые, используя дублирование ранее созданных переменных с другими значениями

2024-01-14 12:41 UTC, mlashina13 approved these changes

2024-01-14 17:38 UTC, Olegas requested changes
Добрый день.
В целом все отлично, но есть пара небольших замечаний. Написал два комментария.
Про форматную строку - минорное, про эффект - надо исправить.

2024-01-14 17:38 UTC, Olegas commented on packages/client/src/App.tsx
> +document.documentElement.dataset.theme = localStorage.getItem('theme') || LIGHT_THEME;
Лучше это убрать в эффект

2024-01-14 17:38 UTC, Olegas commented on packages/client/src/components/ThemeProvider/utils.ts
> +  const theme = `${window?.localStorage?.getItem('theme')}`;
А зачем использовать форматную строку из одного значения? Это лишнее, можно сразу взять window?.localStorage?.getItem('theme')

2024-01-15 20:16 UTC, Olegas approved these changes
Работа принята

2024-01-15 21:33 UTC, merged